config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "cooks#index"
  resources :cooks do
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cook.rb
class Cook < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  validates :recipe_name, presence: true, length: { maximum: 15 }
  validates :recipe,      presence: true, length: { maximum: 1000 }
  validates :image,       presence: true

  def self.search(search)
    if search != ''
      Cook.where('recipe LIKE(?) OR recipe_name LIKE(?)', "%#{search}%", "%#{search}%")
    else
      Cook.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cooks

  validates :nickname, presence: true, length: { maximum: 10 }

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/cooks_controller.rb
class CooksController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @cooks = Cook.includes(:user).order('created_at DESC')
  end

  def new
    @cook = Cook.new
  end

  def create
    @cook = Cook.new(cook_params)
    if @cook.valid?
      @cook.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @cook = Cook.find(params[:id])
  end

  def edit
    @cook = Cook.find(params[:id])
  end

  def update
    @cook = Cook.find(params[:id])
    if @cook.update(cook_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if cook = Cook.find(params[:id])
      cook.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def search
    @cooks = Cook.search(params[:keyword])
  end

  private

  def cook_params
    params.require(:cook).permit(:recipe_name, :recipe, :image).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @cooks = Cook.includes(:user).order('created_at DESC')
    user = User.find(params[:id])
    @nickname = user.nickname
    @cooks = user.cooks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cooks_helper.rb
module CooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cooks/edit.html.erb
<div class="main">

    <div class="contents">
      <%= form_with(model: @cook, local: true) do |form| %>
        <div class="send">
         <%= form.submit "変更する", class: 'submit'%>
        </div>

        <div class="image-upload">
          <%= form.file_field :image, class: 'hidden'%>
            <span class="indispensable">必須</span>
        </div>

        <%# <div class="integer">
          <%= form.text_field :name, class: 'item-text', placeholder: "ニックネーム" %>
          <%# <span class="indispensable">必須</span> %>
        <%# </div>  %>

        <div class="integer">
          <%= form.text_field :recipe_name, class: 'item-text', placeholder: "料理名" %>
          <span class="indispensable">必須</span>
        </div>

        <div class="recipe">
          <%= form.text_area :recipe, class: 'item-area', placeholder: "レシピ"%>
          <span class="indispensable1">必須</span>
        </div>
        <div class="btn">
         <%=link_to 'もどる', root_path, class:"back-btn" %>
        </div>
      <% end %>
    </div>

</div>

app/views/cooks/index.html.erb
 <div class="background-main">
  <div class="main-main">
    <div class="fancybox12">
        <div class="log">

        <% if user_signed_in? %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "post" %>
        <% else %>
        <%= link_to "ログイン", new_user_session_path, class: "post" %>
        <% end%>
        </div>

         <% if user_signed_in? && current_user.id %>
           <h1 class="title">ようこそ<%= current_user.nickname %>さん</h1>
            <% else %>
            <h1 class="title">Cooking</h1>
          <% end %>
           
        <div class="log">
        <% if user_signed_in? %>
          <%= link_to "マイページ", user_path(current_user.id),class: "post" %>
          <% else %>
          <%= link_to "新規登録", new_user_registration_path, class: "post" %>
        <% end %>
        </div>
      </div>

      <div class="post-search">
        <%= form_with(url: search_cooks_path, local: true, method: :get, class: "search-form") do |form| %>
        <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
        <%= form.submit "検索", class: "search-btn" %>
        <% end %>
      </div>

      <div class="post-show">
     <% if user_signed_in? && current_user.id %>
      <a class="post-show1" href="/cooks/new">投稿する</a>
     <% end %>
    </div>

    <div class="item-contents"> 
      <ul class="item-lists">
          <div class="contents-row">
            <% @cooks.each do |cook| %>
              <li>
                <%= link_to cook_path(cook.id) do %> 
                  <div class="content-post"> 
                    <%= image_tag cook.image, class: 'content-post2'%>
                    <p class="name">料理名:<%= cook.recipe_name %></p> 
                    <p class="name">投稿者:<%= cook.user.nickname %></p>
                  </div>
                <% end %> 
              </li>
            <% end %>
          </div>
        </ul>
      </div>

  </div>
</div>

app/views/cooks/new.html.erb
<div class="background">
  <div class="main">

      <div class="contents">
      <%= form_with(model: @cook, local: true) do |form| %>
          <div class="send">
          <%= form.submit "投稿する", class: 'submit'%>
          </div>

      <div class="error-alert-new">
        <div class="error-message-new">
          <%= render "layouts/error_messages", model: form.object %>
        </div>
      </div>

          <div class="upload">
            <%= form.file_field :image, class: 'hidden'%>
          </div>
        
          <h2 class="recipe100">料理名(15字以内)</h2>
          <div class="upload">
          
            <%= form.text_field :recipe_name, autocomplete: "off", class: 'item-text', placeholder: "例:麻婆豆腐" %>
          </div>

          <h2 class="recipe100">レシピ(1000字以内)</h2>
          <div class="upload">
            <%= form.text_area :recipe, autocomplete: "off", class: 'item-area', 
            placeholder: "例:
          木綿豆腐	1丁（300g）
          合いびき肉	80g
          ねぎのみじん切り	1/6本分
          「Cook Do」甜麺醤	小さじ2（10g）
          酒	小さじ1
          にんにくのみじん切り	小さじ1
          「Cook Do」熟成豆板醤	小さじ3（15g）
          「Cook Do」トウチ醤	小さじ1（5g）
          水	1カップ
          「丸鶏がらスープ」	小さじ山盛り1（4g）
          しょうゆ	小さじ1
          水	大さじ1
          片栗粉	大さじ1
          「AJINOMOTO さらさらキャノーラ油」	小さじ1
          粉ざんしょう・好みで	適量
          小ねぎの小口切り	適量
          ＊ 「Cook Do」熟成豆板醤 小さじ１は、チューブで８ｃｍ（約５ｇ）です。"%>
          </div>

          <div class="btn">
          <%=link_to 'もどる', root_path, class:"back-btn" %>
          </div>
        <% end %>
      </div>

    </div>
</div>

app/views/cooks/search.html.erb
<div class="background-search">
  <div class="main-search">
    <div class="fancybox20">
      <h1 class="title-search">検索結果</h1>
      <div class="log-search">
        <%= link_to "もどる", root_path %>
     </div>
    </div>
 
    <div class="post-search">
      <%= form_with(url: search_cooks_path, local: true, method: :get, class: "search-form-search") do |form| %>
      <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input-search" %>
      <%= form.submit "検索", class: "search-btn-search" %>
      <% end %>
    </div>


    <div class="item-contents-search">
      <ul class="item-list-search">
        <div class="contents-row-search">
          <% @cooks.each do |cook| %>
          <li>
            <%= link_to cook_path(cook.id) do%>
            <div class="content-post-search">
              <%= image_tag cook.image, class: 'content-post-search2'%>
              <p class="name-search"><%= cook.recipe_name %></p>
               <p class="name-search">投稿者:<%= cook.user.nickname %></p>
            </div>
            <% end %>
          </li>
          <% end %>
        </div>
      </ul> 
    </div>
  </div>
</div>

app/views/cooks/show.html.erb
<div class="background-show">
  <div class="main-show">
    
    <div class="item-show"> 
      <div class="item-image-content">
        <%= image_tag @cook.image, class:"item-box-image" %>
      </div>
        
      <div class="show-nickname">
        <% if user_signed_in? && current_user.id == @cook.user_id %>
        <% else %>
        <%= link_to @cook.user.nickname, user_path(@cook.user.id), method: :get, class: "show-btn5" %>
        <h2 class="nickname">さんの投稿一覧</h2>
        <% end %>
      </div>

      <div class="item-box">
        
        <table class="table">
            <th class="detail-name">投稿者名</th> 
              <td class="detail-value"><%= @cook.user.nickname %>
              </td> 
              </tr>
            <tr> 
              <th class="detail-name">料理名</th> 
              <td class="detail-value"><%= @cook.recipe_name %>
              </td> 
            </tr>
            <tr> 
            <tr>
              <th class="detail-name2">レシピ</th>
              <td class="detail-value2"><%= @cook.recipe %>
            </tr>
        </table>
      </div> 
    </div>

    <div class="show-btn">
      <% if user_signed_in? && current_user.id == @cook.user_id %>
      <%= link_to '編集', edit_cook_path(@cook.id), method: :get, class: "show-btn1" %>
      <% end %>

      <%= link_to '戻る', root_path, class: "show-btn1"%>

       <% if user_signed_in? && current_user.id == @cook.user_id %>
      <%= link_to '削除', cook_path(@cook.id), method: :delete, class: "show-btn1" %>
      <% end %>
      
    </div>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cooking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <footer>
      <p class="footer1">
      <%= image_tag "stop.png", :size => '20x20' %> Copyright タイトル 2020.<%= image_tag "stop.png", :size => '20x20' %>
      </p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="background-user-show">
  <div class="main-user-show">

    <div class="fancybox15">
    <h1 class="title-show"><%= @nickname %>さんの投稿一覧</h1>
      <div class="log-show">
        <%= link_to "もどる", root_path %>
      </div>
      
    </div>

    <%# <div class="post-show"> %>
     <%# <% if user_signed_in? && current_user.id %> 
      <%# <a class="post-show1" href="/cooks/new">投稿する</a> %>
     <%# <% end %> 
    <%# </div> %>

    <div class="item-contents-show"> 
      <ul class="item-lists-show">
          <div class="contents-show row">
            <% @cooks.each do |cook| %>
              <li>
                <%= link_to cook_path(cook.id) do %>
                  <div class="content_post-show"> 
                    <%= image_tag cook.image, class: 'content_post-show2'%>
                    <p class="name-show">料理名:<%= cook.recipe_name %></p> 
                  </div>
                <% end %>
              </li>
            <% end %>
          </div>
        </ul>
      </div>

  </div>
</div>